name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*'  # still allows tag-triggered release
  workflow_dispatch:  # 👈 enables manual trigger from GitHub UI

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Package extension
        run: |
          cd build
          zip -r ../dark-optin.zip ./*
          cd ..

      - name: Create GitHub release (manual only if no tag)
        if: github.ref_type != 'tag'
        uses: softprops/action-gh-release@v1
        with:
          name: Manual Release ${{ github.run_number }}
          tag_name: manual-${{ github.run_number }}
          files: dark-optin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
